plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
title: [Architecture Diagram]
description: [A set of random architecture diagrams used for blog posts, videos, or talks.]
oogle_analytics: 
theme: jekyll-theme-architect
